name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Install pnpm and dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: Cache NPM dependencies
        uses: actions/cache@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Disable Next.js Telemetry
        run: echo "NEXT_TELEMETRY_DISABLED=1" >> "$GITHUB_ENV"
      - name: Run build
        run: pnpm run build
      # - name: Assume role using OIDC
      #   uses: aws-actions/configure-aws-credentials@v4.0.2
      #   env:
      #     AWS_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
      #   with:
      #     role-to-assume: arn:aws:iam::346733622331:role/cdk-hnb659fds-lookup-role-346733622331-us-east-1
      #     aws-region: $AWS_REGION
      - name: Assume role using AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        run: aws s3 sync out s3://${{ secrets.BUCKET_NAME }} --no-progress --follow-symlinks --delete --region ${{ secrets.AWS_REGION }}
      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2.4
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'