name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
          echo /opt/hostedtoolcache/node/22.10.0/x64/bin >> $GITHUB_PATH
      - name: Check node
        run: |
          ls -alFh /opt/hostedtoolcache/node/
          echo $PATH
          which node
          which npm
          node -v
          npm -v
      - name: Restore NPM node_modules
        uses: actions/cache/restore@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install pnpm and dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: Cache NPM dependencies
        uses: actions/cache@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Disable Next.js Telemetry
        run: echo "NEXT_TELEMETRY_DISABLED=1" >> "$GITHUB_ENV"
      - name: Run build
        run: pnpm run build
      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.CDK_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
      - name: Deploy to S3
        run: aws s3 sync out s3://${{ secrets.BUCKET_NAME }} --no-progress --follow-symlinks --delete --region ${{ secrets.CDK_DEPLOY_REGION }}
      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2.4
        env:
          AWS_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'